- hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb
This enables applications to override the behavior.
> Refactor how access denied errors are handled

- hydra-core/app/models/hydra/datastream/properties.rb
- hydra-core/spec/lib/model_methods_spec.rb
set a custom "depositor" RDF property on the model instead
> Deprecated Properties datastream

- hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
- hydra-core/spec/controllers/downloads_controller_spec.rb
Datastreams don't exist in Fedora 4, we use files instead
> Remove datastream from download

- hydra-core/app/models/concerns/hydra/model_methods.rb
- hydra-core/spec/lib/model_methods_spec.rb
It was not respecting only_if_blank if label was already set
> Revert refactor of set_title_and_label from 5ba3481

- hydra-access-controls/lib/hydra/admin_policy.rb
> Fixed typo in warning messages. Fixes #263

- .travis.yml
- hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb
- hydra-access-controls/spec/unit/embargoable_spec.rb
This should be a significant speedup for projects that use Embargoable
Ref https://github.com/projecthydra-labs/sufia-core/issues/31
> Embargoable#valid? shouldn't create a Lease or Embargo

- hydra-core/app/models/concerns/hydra/content_negotiation.rb
- hydra-core/lib/generators/hydra/head_generator.rb
- hydra-core/spec/controllers/catalog_controller_spec.rb
> Changes content header for JSON-LD mimetype.

- hydra-core/app/controllers/concerns/hydra/controller/search_builder.rb
I think the change is what was meant. Or else I don't know what is meant be "collection".
> Correct comment

- hydra-core/app/search_builders/hydra/search_builder.rb
- hydra-core/lib/generators/hydra/head_generator.rb
- hydra-core/lib/generators/hydra/templates/catalog_controller.rb
- hydra-core/spec/controllers/catalog_controller_spec.rb
- hydra-core/spec/search_builders/search_builder_spec.rb
- hydra-core/spec/test_app_templates/Gemfile.extra
> Generate AccessControlsEnforcement into SearchBuilder

- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/lib/hydra/config.rb
- hydra-access-controls/lib/hydra/policy_aware_ability.rb
- hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb
- hydra-access-controls/spec/support/mods_asset.rb
- hydra-access-controls/spec/unit/admin_policy_spec.rb
- hydra-access-controls/spec/unit/config_spec.rb
- hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb
- hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb
- hydra-core/hydra-core.gemspec
Still need to fix: https://github.com/projecthydra/active_fedora/issues/1030
> Updates for active_fedora 9.10.0

- Rakefile
- hydra-core/Rakefile
Also, don't run docs on the ci server, since travis doesn't have a
mechanism for fetching the artifacts
Fixes #344
> Add a spec task to hydra-core

- hydra-core/lib/tasks/hydra.rake
Depends on https://github.com/projecthydra/active_fedora/pull/1078
> Using generated config files for fedora & solr

- hydra-core/app/models/hydra/content_negotiation/replacing_graph_finder.rb
- hydra-core/spec/models/content_negotiation/replacing_graph_finder_spec.rb
> Use the correct base url in content negotiation

- .travis.yml
Hi. Islandora <3's Hydra.
Let me know if you need an iCLA and I'll send one along.
> Remove irc notifications... because Slack.

- hydra-core/lib/tasks/hydra.rake
Since both Princeton and @jrochkind were doing this, it seems worth adding to the default Rake tasks.
> Adding Rake task for development servers without Rails

- solr/config/schema.xml
> Add Solr dateRange field type and dynamic fields to schema.xml

- hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
Because `render nothing:true` is not supported in Rails 5.1
This fixes the failure seen in #426
> Revert part of #421

- hydra-access-controls/spec/factories.rb
- hydra-access-controls/spec/services/embargo_service_spec.rb
- hydra-access-controls/spec/services/lease_service_spec.rb
- hydra-access-controls/spec/spec_helper.rb
- hydra-access-controls/spec/unit/ability_spec.rb
- hydra-access-controls/spec/unit/accessible_by_spec.rb
- hydra-access-controls/spec/unit/admin_policy_spec.rb
- hydra-access-controls/spec/unit/permission_spec.rb
- hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb
- hydra-core/hydra-core.gemspec
- hydra-core/spec/factories.rb
- hydra-core/spec/models/user_spec.rb
- hydra-core/spec/spec_helper.rb
- hydra-head.gemspec
* Removing yard from top-level gemspec (see #428)
* Upgrading FactoryGirl to FactoryBot
> Updating dependencies

- Gemfile
- hydra-access-controls/app/models/role_mapper.rb
- hydra-access-controls/app/search_builders/hydra/access_controls/policy_aware_search_builder.rb
- hydra-access-controls/app/search_builders/hydra/access_controls/search_builder.rb
- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/lib/active_fedora/accessible_by.rb
- hydra-access-controls/lib/hydra/access_controls_enforcement.rb
- hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb
- hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb
- hydra-core/app/controllers/concerns/hydra/catalog.rb
- hydra-core/lib/generators/hydra/head_generator.rb
- hydra-core/spec/search_builders/search_builder_spec.rb
> Use the new Blacklight::AccessControls::SearchBuilder

- .travis.yml
> Bump to latest minor/patch versions for test matrix

- .travis.yml
- Gemfile
- hydra-core/hydra-core.gemspec
RAILS_VERSION was misspelled and thus not being applied properly by travis.
https://github.com/samvera/hydra-head/issues/439
> Fix typo found by @RudyOnRails

- RELEASING_HYDRA_HEAD.md
> Change Hydra to Samvera

- .github/CONTRIBUTING.md
Spotted by @mark-dce in https://github.com/samvera/hyrax/pull/2958.
> Update github documentation links

- .github/CONTRIBUTING.md
- .github/SUPPORT.md
- LICENSE
- README.md
Closes #451 Closes #452 Closes #449
> Add CCMWG templates.

- .coveralls.yml
- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/spec/spec_helper.rb
- hydra-core/hydra-core.gemspec
- hydra-core/spec/spec_helper.rb
- hydra-head.gemspec
> Integrates reporting for Coveralls

- hydra-core/lib/hydra-head/version.rb
> Prepare for release

- hydra-core/lib/hydra-head/version.rb
Reverts samvera/hydra-head#465
In order to follow the release process outlined here: https://github.com/samvera/hydra-head/blob/master/RELEASING_HYDRA_HEAD.md
> Revert "Prepare for release"

- .travis.yml
- hydra-access-controls/spec/support/user.rb
> Test against rails 5.2

- .circleci/config.yml
- hydra-access-controls/spec/spec_helper.rb
- hydra-core/spec/spec_helper.rb
> Updates the CircleCI configuration to test against Ruby releases 2.6.3, 2.5.5, and 2.4.6

- hydra-access-controls/hydra-access-controls.gemspec
- hydra-core/hydra-core.gemspec
- hydra-head.gemspec
The old homepage didn't exist anymore.
> Update homepage in all the gemspecs

- .circleci/config.yml
Re: samvera/maintenance#20
Re: samvera/maintenance#21
> Remove CircleCI default ruby/rails versions

- .circleci/config.yml
- Gemfile
- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/tasks/hydra-access-controls.rake
- hydra-head.gemspec
- spec/test_app_templates/Gemfile.extra
This is a work in progress, but demonstrates what needs to be updated to resolve #485
> Updates the CircleCI configuration and active-fedora for solr/conf paths 

- hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb
- hydra-access-controls/spec/unit/embargoable_spec.rb
Backport of #517 to 11.x in preparation of a 11.0.1 release since releasing the default branch would require a major release.
> Ensuring embargo/lease changes are persisted

- .circleci/config.yml
- Gemfile
- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/lib/active_fedora/accessible_by.rb
- hydra-access-controls/lib/hydra/ability.rb
- hydra-access-controls/lib/hydra/access_controls_enforcement.rb
- hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb
- hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb
- hydra-core/app/controllers/concerns/hydra/catalog.rb
- hydra-core/app/helpers/blacklight_helper.rb
- hydra-core/app/helpers/hydra/blacklight_helper_behavior.rb
- hydra-core/app/models/hydra/search_builder.rb
- hydra-core/app/services/hydra/search_service.rb
- hydra-core/hydra-core.gemspec
- hydra-core/lib/generators/hydra/head_generator.rb
- hydra-core/spec/controllers/catalog_controller_spec.rb
- hydra-core/spec/helpers/blacklight_helper_spec.rb
- hydra-core/spec/search_builders/search_builder_spec.rb
- hydra-head.gemspec
- spec/test_app_templates/Gemfile.extra
- spec/test_app_templates/lib/generators/test_app_generator.rb
This might require a major version bump, although if someone can chime in about what incompatibilities existed with #498, maybe they can be addressed and this could be a new minor release.
> Relax dependencies to support Blacklight 7 & Rails 6

- hydra-head.gemspec
relax rails dependency to <7 for consistency with other gems
> Require ruby 2.5 or greater

- .circleci/config.yml
- hydra-head.gemspec
Upgrade development dependencies and test with latest ruby and rails.
> Upgrade dependencies

- .circleci/config.yml
> Adding the CircleCI configuration for nightly test suite executes

- .circleci/config.yml
- Gemfile
- Rakefile
- hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb
- hydra-access-controls/app/validators/hydra/future_date_validator.rb
- hydra-access-controls/hydra-access-controls.gemspec
- hydra-access-controls/lib/hydra/ip_based_groups.rb
- hydra-access-controls/lib/hydra/role_mapper_behavior.rb
- hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
- hydra-core/hydra-core.gemspec
- hydra-core/lib/generators/hydra/head_generator.rb
- hydra-head.gemspec
- spec/test_app_templates/Gemfile.extra
> Test with ruby 3
