hydra-access-controls/hydra-access-controls.gemspec, hydra-core/hydra-core.gemspec, hydra-core/spec/test_app_templates/Gemfile.extra
Also added versions to gems that didn't have any. Fixes #192
Removed unused block_helpers depenency
=> Update gemspecs to point at ActiveFedora 9.0.0

hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb, hydra-core/app/controllers/concerns/hydra/controller/search_builder.rb, hydra-core/lib/generators/hydra/templates/catalog_controller.rb
Creates a module for overriding Blacklight's search_builder method. This module can be included in any controller and is separate from Hydra::Controller::ControllerBehavior.
This has been tested against Sufia and corrects the problems found in projecthydra/sufia#953
=> Using Hydra::Controller::SearchBuilder

hydra-access-controls/lib/hydra/config.rb, hydra-core/app/models/concerns/hydra/content_negotiation.rb, hydra-core/app/models/hydra/content_negotiation/clean_graph_repository.rb, hydra-core/app/models/hydra/content_negotiation/fedora_uri_replacer.rb, hydra-core/app/models/hydra/content_negotiation/graph_finder.rb, hydra-core/app/models/hydra/content_negotiation/replacing_graph_finder.rb, hydra-core/hydra-core.gemspec, hydra-core/lib/generators/hydra/head_generator.rb, hydra-core/spec/controllers/catalog_controller_spec.rb
Now that Fedora 4 exposes an RDF-Source for each stored asset, it's possible to
expose that metadata through the interface. This provides that as well as a
mechanism to change the URIs that typically come out of Fedora.
=> Add Content Negotiation

hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb
Modifies Hydra::ControllerBehavior to use more explicit syntax when redirecting a user.  This makes things more consistent when other engines rely on that behavior.
Without this, tests like this one in the curation_concerns gem will break because the code does not know how to find the desired route: https://github.com/pulibrary/hydra-curation_concerns/blob/rename_to_cc/spec/controllers/curation_concerns/generic_works_controller_spec.rb#L75-L78
Sorry I haven't had time to write a test for hydra-head to cover this.  I don't fully understand why this was breaking in curation_concerns, but the change in hydra-head only makes the code more explicit about what's happening, so I'm hoping you'll accept it :smile_cat:
=> Explicit route syntax when redirecting to main_app routes

hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/spec/unit/permissions_spec.rb
Fixes #267
The solr document for the object that has permissions gets written
before the autosave association callback is run. So calling .to_solr
after saving the object gives the correct result, but that wasn't actually
the result that was written to solr.
=> Don't index permissions marked for destruction

hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb, hydra-access-controls/spec/unit/visibility_spec.rb
Going from authenticated visibility to public visibility used to leave the authenticated permission objects behind and add the public one as well. This wasn't a problem with authentication since public is more permissive than authenticated anyway. But some UI code would get confused and think the document visibility is both public and authenticated. Sufia in particular would check the authenticated check box in the permissions edit form instead of public, which was clearly wrong.
=> Fix permissions when setting visibility to public from authenticated.

hydra-core/lib/generators/hydra/head_generator.rb
The install generator currently injects MIME types before every newline, which results in multiple MIME type registrations and lots of warnings in the console.  This PR eliminates all the warnings and results in a tidier . Thanks to @jcoyne for the sleuthery on this one.
Fixes projecthydra-labs/hydra-pcdm#132
=> Append MIME types in the install generator. Fixes projecthydra-labs/hydra-pcdm#132

hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb, hydra-core/spec/controllers/downloads_controller_spec.rb
We are having issues with downloading files larger than 300MB.  Sometimes the browser downloads the entire thing, other time it does not.  Adding the length back in gives us consistent download behavior.
@jcoyne does this undo your streaming change?  I looked at the comments on your bug to find the cache solution, but I am not 100% sure I did not foul things up...
=> Adding in the Content-Length header

hydra-access-controls/lib/hydra/role_mapper_behavior.rb, hydra-access-controls/spec/unit/role_mapper_spec.rb
This raises an error when the environment isn't found instead of a Nil
pointer error like:
```
NoMethodError (undefined method `each_with_object' for nil:NilClass):
hydra-access-controls (9.2.2) lib/hydra/role_mapper_behavior.rb:35:in
`byname'
hydra-access-controls (9.2.2) lib/hydra/role_mapper_behavior.rb:20:in `roles'
hydra-access-controls (9.2.2) lib/hydra/user.rb:18:in `groups'
```
=> Role mapper should fetch keys

CONTRIBUTORS.md, HISTORY.textile, hydra-access-controls/README.textile, hydra-access-controls/lib/hydra/ability.rb, hydra-access-controls/spec/unit/ability_spec.rb
hydra-access-controls provides CanCan abilities for `:read`, `:edit`, and `:download` permissions, but not `:discover`.  This change adds abilities for `:discover`.
The implementation parallels that used for `:read` and `:edit` permissions.  It assumes that if a document can be `:read`, then it can also be `:discover`ed, but not vice-versa.
I added/updated unit tests accordingly.  `ability_spec.rb` has a comment that references some request specs, but I couldn’t find those in the codebase so I didn’t add any of those specs.
=> Provide CanCan abilities for discover permissions

hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
Resolves bug discussed on list: https://groups.google.com/forum/#!searchin/hydra-tech/sufia$20internal/hydra-tech/UMnWsDxSGdY/KzB70wSMBwAJ
thumbnails fail to load via webrick, example trace: 
[2015-10-14 16:33:08] ERROR NoMethodError: undefined method `split' for 5157:Fixnum
/home/jhallida/.rvm/gems/ruby-2.1.7@sufia6/gems/rack-1.6.4/lib/rack/handler/webrick.rb:99:in `block in service'
/home/jhallida/.rvm/gems/ruby-2.1.7@sufia6/gems/rack-1.6.4/lib/rack/utils.rb:490:in `block in each'
/home/jhallida/.rvm/gems/ruby-2.1.7@sufia6/gems/rack-1.6.4/lib/rack/utils.rb:489:in `each'
/home/jhallida/.rvm/gems/ruby-2.1.7@sufia6/gems/rack-1.6.4/lib/rack/utils.rb:489:in `each'
/home/jhallida/.rvm/gems/ruby-2.1.7@sufia6/gems/rack-1.6.4/lib/rack/handler/webrick.rb:91:in `service' …
=> Make content-length a string so webrick will be happy.

hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb, hydra-access-controls/spec/unit/visibility_spec.rb
This gives a single method to override if you want to add your own
custom visibility type.  Prior to this method being available, you would
have to override `public_visibility!`, `registered_visibility!` and
`private_visibility!` to be aware of the new visibility.
=> Added represented_visibility method

hydra-access-controls/hydra-access-controls.gemspec, hydra-access-controls/lib/hydra-access-controls.rb, hydra-access-controls/lib/hydra/ability.rb, hydra-access-controls/lib/hydra/access_controls_enforcement.rb, hydra-access-controls/lib/hydra/permissions_cache.rb, hydra-access-controls/lib/hydra/permissions_query.rb, hydra-access-controls/lib/hydra/policy_aware_ability.rb, hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb, hydra-access-controls/lib/hydra/user.rb, hydra-access-controls/spec/unit/ability_spec.rb, hydra-access-controls/spec/unit/access_controls_enforcement_spec.rb, hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb, hydra-core/app/controllers/concerns/hydra/catalog.rb, hydra-core/app/controllers/concerns/hydra/controller/search_builder.rb, hydra-core/lib/generators/hydra/templates/catalog_controller.rb, hydra-core/spec/controllers/catalog_controller_spec.rb, hydra-core/spec/controllers/downloads_controller_spec.rb
I ported the "read" & "discover" parts of hydra-access-controls into a new gem, blacklight-access_controls, so that blacklight apps can use access controls too.  The new gem is here:
https://github.com/projectblacklight/blacklight-access_controls
I removed the ported code from hydra-head, and made hydra-head depend on blacklight-access_controls so that we won't have duplicate/divergent code.
Ping @jcoyne and @cam156 for code review.
=> Extracted some of hydra-access-controls code to a new gem, blacklight-access_controls.

hydra-access-controls/hydra-access-controls.gemspec
It's no longer necessary since we aren't supporting Rails 3
=> Remove hard dependency on sass-rails.

hydra-core/lib/generators/hydra/head_generator.rb, hydra-core/lib/generators/hydra/templates/config/initializers/hydra_config.rb
Previously if you didn't specify the model name this line would have
been generated into the config:
Now it's:
=> Use the template to set the model name

hydra-access-controls/lib/hydra/config.rb, hydra-core/app/models/hydra/content_negotiation/fedora_uri_replacer.rb, hydra-core/spec/controllers/catalog_controller_spec.rb
Because the generated uri may depend on other triples in the graph such
as fedora:hasModel
=> Call id_to_resource_uri with a graph

hydra-core/lib/generators/hydra/templates/catalog_controller.rb
These are already added by default in
Blacklight::AccessControls::Enforcement https://github.com/projectblacklight/blacklight-access_controls/blob/master/lib/blacklight/access_controls/enforcement.rb#L20
Note: we should update Dive Into Hydra to remove access controls on the
search builder
=> Don't explicitly add access controls

hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/spec/unit/permissions_spec.rb
When an object using permssions is destroyed, destroy all the associated
permissions.
Fixes #290
=> Destroy permissions when an object is destroyed

hydra-access-controls/app/models/hydra/access_control.rb, hydra-access-controls/spec/unit/collection_relationship_spec.rb
delegate `each`, `all?`, `any?`, `first`, `include?` and `destroy_all`
=> Implement more methods on the AccessControl::CollectionRelationship

hydra-core/lib/generators/hydra/templates/config/role_map.yml
So that it doesn't imediately throw a key error when run in production
mode.
=> Add an empty 'production' key to role_map

hydra-core/app/models/hydra/content_negotiation/clean_graph_repository.rb, hydra-core/app/models/hydra/content_negotiation/fedora_uri_replacer.rb, hydra-core/app/models/hydra/content_negotiation/replacing_graph_finder.rb
This allows us to use a more dyanmic replacement function that has
inputs such as the request context
=> Pass replacment function to CleanGraphRepository

hydra-access-controls/hydra-access-controls.gemspec
Also adjust formatting of license identification string to match formal recommendations of:
- http://guides.rubygems.org/specification-reference/#license=, referencing
- http://spdx.org/licenses/Apache-2.0.html
=> Bump blacklight-access_controls version

hydra-head.gemspec
So... if we are including yard as a dev dependency, we should include RedCloth.
Also corrected the license string format to the formal `Apache-2.0` code.
=> RedCloth is required to run yardoc

.travis.yml, Gemfile, hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/spec/unit/permissions_spec.rb, hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb, hydra-head.gemspec
Fixes an issue identified in Sufia where the UI allows the user to both delete and add the same permission.
See projecthydra/sufia#2821
=> Remove permissions if they specify delete and update at the same time

hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/spec/unit/permissions_spec.rb
Previously, `remove_bad_deletes` wasn't counting existing delete permissions correctly, and non-delete permissions we counting as `nil` in the array when they should have been absent.
=> Correct error in detemining delete permissions

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-access-controls/spec/unit/permission_spec.rb
Because the validation flag isn't set in the call to RDF::URI.new it is possible to save an invalid URI if you have an agent with a space it it's name (e.g. 'John Doe' or 'Hydra developers').  In this case, reading the permissions back on the owning AF::Base object throws a RuntimeError of 'no agent'.  This PR escapes the agent name when building the URI and decodes it on read.
=> Escape agent to avoid invalid agent URIs

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-access-controls/spec/unit/permission_spec.rb
This coerces the arg to a string early so that it can be URI encoded later.
=> Recent change to Permission class removed automatic string interpolation on `name` argument.

hydra-access-controls/lib/hydra/role_mapper_behavior.rb, hydra-access-controls/spec/unit/role_mapper_spec.rb
It's added by blacklight-access-control here:
https://github.com/projectblacklight/blacklight-access_controls/blob/f0b003ef6006b778c460d2b399c026d3b92052cf/lib/blacklight/access_controls/ability.rb#L102
=> Remove registered pseudo-group from RoleMapper

hydra-core/spec/controllers/catalog_controller_spec.rb, hydra-core/spec/controllers/downloads_controller_spec.rb
This removes these deprecation warnings:
```
DEPRECATION WARNING: ActionController::TestCase HTTP request methods
will accept only keyword arguments in future Rails versions.
```
=> Use the new way of running controller tests

hydra-core/lib/tasks/hydra.rake
Based off discussion in #381, this PR updates the `hydra:server` rake task to respect the `HOST` environment variable. The `HOST` environment variable has also been introduced on Rails `master` (see https://github.com/rails/rails/pull/25688). So, this is preemptive support for that new option.
Behavior is now as follows:
- `rake hydra:server` by default continues to simply bind to localhost
- `HOST="0.0.0.0" rake hydra:server` will instead bind to all IPs. I've tested this option using [hydra-vagrant](https://github.com/projecthydra-labs/hydra-vagrant) and it allows the application running on the VM to now be accessible from the host machine.
=> Update hydra:server to support HOST env variable

hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/app/models/hydra/access_control.rb, hydra-access-controls/spec/unit/permissions_spec.rb
Prevents `object.permissions` from returning rows that have been
destroyed.
Ref https://github.com/projecthydra/sufia/issues/3033
Ref https://github.com/projecthydra/sufia/issues/2820
=> Clear cache when removing permissions

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-access-controls/spec/unit/permissions_spec.rb
Ref https://github.com/projecthydra/sufia/issues/2820
=> Reset cached values after updating source data

hydra-access-controls/lib/hydra/shared_spec/group_service_interface.rb, hydra-access-controls/spec/unit/role_mapper_spec.rb, hydra-core/spec/models/user_spec.rb
We are working at pushing Hyku's rolify behavior into the
`User.group_service` interface. This is our first step to begin to
better enforce the interface of the group service.
=> Adding `it_behaves_like 'a Hydra group_service interface'`

.travis.yml
Because presently there's no version of the devise gem that supports
Rails 5.1 https://rubygems.org/gems/devise
=> Test using Rails 5.0

hydra-core/lib/generators/hydra/head_generator.rb
Fixes #409 
I placed this in the `ingest_test_framework` method since it seemed most relevant there. Please let me know if it should instead go in its own method.
=> generator should install rspec

hydra-core/lib/generators/hydra/templates/config/blacklight.yml
There was no legitimate reason to have structurally and semantically different behavior here.
=> Respect SOLR_URL even in test

hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
instead of a loop of response.stream.write's.
Rails still streams with this new implementation. But it is delivering the HTTP response
headers a lot faster this way, almost immediately.
With the previous way, with a 1G original file accessed via
/downloads, I was seeing an 11 second wait even to get HTTP headers.
Not sure why, it could be because it takes that long to even get
the first byte from fedora, and it's not sending anything until it does?
But I tried to mess around with things using the response.stream.write
API, and was not able to improve things.
Browsers are willing to wait that long, but it's not a great UX -- you get
a 'waiting for connection' popup in chrome until the HTTP  headers (in my
case 11 seconds later), only at that point does it show up as a download in progress. …
=> stream_body uses response.body = iostream

hydra-core/hydra-core.gemspec
It has a security vulnerability https://nvd.nist.gov/vuln/detail/CVE-2017-17042
and we aren't using it anyway.
=> Drop yard as a dependency

spec/test_app_templates/lib/generators/test_app_generator.rb
Ref https://github.com/projectblacklight/blacklight/pull/1808
This isn't going to do anything until Blacklight 6.13 is released.
=> Skip solr install because the active-fedora installer will do it

hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
We have been seeing lots of extra memory usage when downloading large
files from Fedora. There was a version of this fix applied in #421, but
it was reverted in #427. This uses the recommended technique of setting
the controller's response_body to the stream.
In looking through the ActionController source, this should both start
the output (sending headers), and flag the render as having performed,
so implicit template resolution/rendering will be skipped.
I have another version of this patch against 10.5.0, but there is no branch in the main repository for 10.x. It would be good to determine whether Hyrax 1.x can use 11.0 or if there should be a 10.5.1 or 10.6.0 release -- this is a major threat to production applications with large files. We were seeing ~25 puma workers per hour …
=> Fix download streaming with self.response_body=

.travis.yml, CONTRIBUTORS.md, README.md, hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb, hydra-access-controls/spec/factories.rb, hydra-access-controls/spec/services/embargo_service_spec.rb, hydra-access-controls/spec/services/lease_service_spec.rb, hydra-access-controls/spec/spec_helper.rb, hydra-access-controls/spec/unit/ability_spec.rb, hydra-access-controls/spec/unit/accessible_by_spec.rb, hydra-access-controls/spec/unit/admin_policy_spec.rb, hydra-access-controls/spec/unit/permission_spec.rb, hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb, hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb, hydra-core/hydra-core.gemspec, hydra-core/spec/factories.rb, hydra-core/spec/models/user_spec.rb, hydra-core/spec/spec_helper.rb, hydra-head.gemspec, solr/config/schema.xml, spec/test_app_templates/lib/generators/test_app_generator.rb
This PR backports most changes to master since 10.5.0 except ones that I felt might be backwards incompatible.  This is in preparation for cutting a 10.5.1 release.
Commits left out of this pull request:
* Updating to use AF12 (56152a6aa3eba04e4155b7eaf74a317fdd7ec447)
* No need to maintain a configuration. ActiveFedora generates it (667d669c695e5f7ee4390e3d70fccbaa2a5f8a3f)
* Use the new Blacklight::AccessControls::SearchBuilder (84700aa677b2b3fbd8e0c6cffd251a4909603bcc)
* Preparing for 11.0.0.rc1 release (e09a819152f1cf6f96fdff528d4baa9e3ff9d541)
@projecthydra/hydra-contributors
=> Backports for 10.5.1

hydra-access-controls/lib/hydra-access-controls.rb
They were only required for Rails 3 which is no longer supported.
=> Remove autoload paths

hydra-access-controls/hydra-access-controls.gemspec
This is leading to a RuntimeError on nurax:
>You may not use Blacklight::AccessControls::SearchBuilder and include Blacklight::AccessControls::Enforcement on SearchBuilder at the same time
=> hydra-access-controls 10.x is not compatible with blacklight-access_controls 0.7

.coveralls.yml, hydra-access-controls/hydra-access-controls.gemspec, hydra-access-controls/spec/spec_helper.rb, hydra-core/hydra-core.gemspec, hydra-core/spec/spec_helper.rb, hydra-head.gemspec
Forward port of #457 now that master has been rolled back to the 10.x line. 
This is an alternative to #458.  
Resolves #448.
=> Integrating support for Coveralls and restructuring the integration of SimpleCov

hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb, hydra-access-controls/spec/unit/permissions_spec.rb
ACLs are real Fedora objects. Saving them involves a round trip, and other complications. It turns out we don't actually need to do this, and can just `build` a missing ACL.
Fixes #453.
=> Don't create ACLs agressively when accessing permissions

hydra-access-controls/app/services/hydra/embargo_service.rb, hydra-access-controls/app/services/hydra/lease_service.rb, hydra-access-controls/spec/services/embargo_service_spec.rb
ActiveFedora 12.1.0 brings a new solr schema which switches from the deprecated solr.TrieDateField (to be removed in solr 8) to solr.DatePointField. While the TrieDateField allowed queries like date_dtsi:*, DatePointField only allows single value and range queries so this example query needs to change to date_dtsi:[* TO *]. Luckily the latter also works in TrieDateField. This PR updates both the embargo and lease search builders to use the [* TO *] query to work with both types of solr fields.
=> Use [* TO *] to work with old and new versions of AF and Solr

hydra-access-controls/hydra-access-controls.gemspec, hydra-access-controls/lib/active_fedora/accessible_by.rb, hydra-access-controls/lib/hydra/access_controls_enforcement.rb, hydra-access-controls/lib/hydra/policy_aware_access_controls_enforcement.rb, hydra-access-controls/spec/unit/policy_aware_access_controls_enforcement_spec.rb, hydra-core/app/controllers/concerns/hydra/catalog.rb, hydra-core/app/models/hydra/search_builder.rb, hydra-core/lib/generators/hydra/head_generator.rb, hydra-core/spec/search_builders/search_builder_spec.rb, spec/test_app_templates/lib/generators/test_app_generator.rb
Reverts samvera/hydra-head#475
I think this PR introduced backwards incompatible changes that break existing applications (and I believe is untested against those apps).  I'm not ready to resolve this yet or make a 11.0 release so I'd like to revert this for now.
=> Revert "Bump Blacklight-access_controls to 6.0"

Gemfile, hydra-access-controls/app/models/hydra/access_control.rb, hydra-core/hydra-core.gemspec, hydra-head.gemspec
Fixes #500 ; refs samvera/hyrax#3974
`build` a permission object when setting permissions_attributes instead of using `create`.
Fixes Circle build with sprockets 4.0 workaround.
Removes old versions of ruby and rails as per #500 
A past commit (a5c4dd58001a961074395cafee09f496ddc39fdb) changed the creation of an AccessControl from using `create` to using `build` to avoid orphan objects. That change caused hyrax to be unable to create a work when also adding user/group permissions, resulting in a 'no agent' error.
It appears this is caused by the AccessControl not being saved correctly, or thinking it has not changed since being persisted, when triggered by saving the work object. Changing the permission relationship `create` to `build` avoids this issue and may further reduce the number …
=> Build permission relations, drop old rubies/rails

.circleci/config.yml, hydra-head.gemspec
Fixes #503 .  Support for Rails 6 (#504) depends on an upgrade of blacklight so that is a larger task.  Maybe it makes sense to try and do that before release too?
=> Support ruby 2.7 and drop support for rails 5.1

hydra-access-controls/spec/unit/accessible_by_spec.rb
Testing equality was causing this test to fail whenever the search results returned the objects in a different order than expected.  The ordering is not important for this feature so switching to inclusion avoids the intermittently failing test.
Fixes #506.
=> Test for inclusion instead of equality to allow for different ordering

hydra-access-controls/hydra-access-controls.gemspec
Also Bump version of rake to 12.3.3 for security patch
hydra-access-controls should have switched to requiring ruby 2.4+ like its parent and sibling gems when 11.0.0 was released but it was overlooked.
=> Bump required ruby version to 2.4 to match hydra-head and hydra-core

hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb, hydra-access-controls/spec/unit/embargoable_spec.rb, hydra-access-controls/spec/unit/visibility_spec.rb
Prior to this PR, dirty tracking of visibility was implemented in a limited, custom way.  `#visibility_changed?` with no arguments was the only method implemented.  Switching to ActiveModel::Dirty makes dirty tracking support more standard and with more available methods (including `#visibility_changed?` with `:from` and `:to` keyword arguments).
Changes proposed in this pull request:
* Implement ActiveModel::Dirty for visibility
* Make child gems match parent hydra-head rails version dependencies
* Remove outdated handling of activemodel < 4.2 in unit specs
=> Visibility dirty tracking

hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb, hydra-access-controls/spec/unit/embargoable_spec.rb
Prior to this commit, when a user changed the Embargo or Lease of an
already persisted object, that change was not persisted.
With this commit, those changes are persisted.
Related to samvera/hyrax#4537
Related to samvera/hyrax#4534
=> Ensuring embargo/lease changes are persisted

.circleci/config.yml, hydra-access-controls/lib/hydra-access-controls.rb, hydra-access-controls/spec/factories/objects.rb, hydra-access-controls/spec/factories/user.rb, hydra-access-controls/spec/spec_helper.rb, hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb, hydra-core/spec/controllers/catalog_controller_spec.rb, hydra-core/spec/controllers/downloads_controller_spec.rb, hydra-core/spec/spec_helper.rb, hydra-head.gemspec
Changes proposed in this pull request:
* Unescape filenames in content-disposition for rails 6 to maintain current behavior and avoid double encoding (See https://github.com/rails/rails/pull/33829)
* Add ACL acronym instead of depending on it already existing
* Refactor factories so they can load under rails 6
* Add factory_bot_rails as a dev dependency
* Make tests compatible with rails 6 
=> Rails 6 support

hydra-access-controls/hydra-access-controls.gemspec, hydra-access-controls/spec/unit/embargoable_spec.rb, hydra-core/hydra-core.gemspec
This PR clears up inconsistencies between the gemspecs of hydra-head and its two child gems.  While hydra-head depends on rails >=5,2, < 7, both hydra-access-controls and hydra-core allow for rails components as low as 4.0.  This seems like an oversight to me where the two child gems should be made to match hydra-head, but if any application was depending on just a child gem and not hydra-head then this change might necessitate a major version bump.  FWIW all three gems are only tested with rails 5.2 and 6.0 at the moment.
Also removes outdated handling of activemodel < 4.2 in unit specs
=> Make child gems match parent hydra-head rails version dependencies

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-head.gemspec
Address deprecated URI.escape method and related methods. In applications using Ruby 2.7 and above this deprecation now creates a warning-level message which clogs up logs and makes it hard to diagnose issues with Hydra::AccessControls. 
Changes proposed in this pull request:
* Build the RDF::URI by giving the broken-down portions of the URI, rather than giving it the entire thing as a string. This allows the RDF gem to use the appropriate escaping for the various portions of the URI, and it can then recognize and re-normalize the "fragment" portion of the URI. From what I'm seeing, the standard is currently that the "fragment" portion of the URI, also referred to as the URL.hash, should not be percent-decoded; however, we are continuing to do so in order to ensure consistent data. 
* I …
=> Uri escape

hydra-head.gemspec
Previous merged PR upgraded the Rails dependency on the 11.x branch, this PR reverts this change in order to allow for a patch-level release of the URI deprecation fix. 
See [Instructions for
Contributors](http://github.com/samvera/hydra-head/wiki/For-Contributors) for how to address dependencies with Engine Cart in development.
=> Return actual gem dependency to prior

RELEASING_HYDRA_HEAD.md
rake all:release creates a GitHub tag, and fails if the release was 
already tagged.  Updated the order of operations in 
RELEASING_HYDRA_HEAD.md to reflect this.
Changes proposed in this pull request:
* Documentation changes only.
=> Reflect order requirement of release rake task in release document

hydra-access-controls/app/models/hydra/access_controls/permission.rb
The previous fix for the URI.escape deprecation accidentally left in one instance of it (see https://github.com/samvera/hydra-head/pull/525), probably due to a commit confusion. This takes it out and should solve the issue for this gem once and for all. 
=> Take URI.escape back out

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-head.gemspec
Revert changes made to avoid deprecation warnings for URI.escape and URI.unescape.  Later testing showed that while the test suite passed without modification there are some scenarios that weren't being tested that had changes in how they encoded.  The existing test is for spaces which behave the same as they did before but agent names (group names or email addresses) with a `+` or `%20` changed behavior and are now encoding the same as spaces.  This is a collision which could be problematic as you can see below.  Each of the three examples for both group and user are unique and possible but end up getting the same stored value.
As discussed on the tech call the proposed course of action is to merge this revertion, cut a new patch release (11.0.6), and yank 11.0.5 and 11.0.4.  This change …
=> Revert URI.escape and URI.unescape changes

hydra-access-controls/app/models/hydra/access_controls/permission.rb, hydra-access-controls/spec/unit/permission_spec.rb
Create private methods to insulate from actual implementation
Add some additional test cases for escaping
Works around deprecation warning to close #531
=> Use an explicit parser when encoding/decoding agent names

hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb, hydra-access-controls/spec/unit/embargoable_spec.rb
it should be possible to maintain existing embargo/lease data even after the
release date has passed. validating future dates on all saves prevents this;
only do this on `:create` actions instead.
=> limit embargo/lease date validation to create

.circleci/config.yml
Fixes #538 
This PR adds the Circle CI step that fails if the branch name is master.
=> Updating the CircleCI configuration to check for a master branch

hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb
Not providing .html is deprecated in Rails 6.0, doesn't work in 6.1.
=> Provide an exact path for render_404.

.circleci/config.yml, README.md
This is necessary in order to request from the community renewed efforts for maintenance, and to direct those outside of the community to the Samvera Slack.
=> Updating the Product Owner information in preparation for the 2022 autumn request for maintenance

.circleci/config.yml, Gemfile, hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb, hydra-access-controls/hydra-access-controls.gemspec, hydra-core/hydra-core.gemspec, hydra-head.gemspec, spec/test_app_templates/Gemfile.extra
Part of https://github.com/samvera/maintenance/issues/161
Also drop testing on unsupported ruby/rails versions
The one substantial change in this PR is refactoring the visibility methods into a submodule that gets included to workaround a timing issue with changes in ActiveModel's `define_attribute_methods`.
=> Test with Rails 7.2

hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb, hydra-access-controls/spec/unit/embargoable_spec.rb
Prior to this commit, when a user changed the Embargo or Lease of an
already persisted object, that change was not persisted.
With this commit, those changes are persisted.
Related to samvera/hyrax#4537
Related to samvera/hyrax#4534
=> Ensuring embargo/lease changes are persisted (backport)

.circleci/config.yml, Gemfile, hydra-access-controls/hydra-access-controls.gemspec, hydra-core/hydra-core.gemspec, hydra-core/spec/controllers/catalog_controller_spec.rb, hydra-core/spec/helpers/blacklight_helper_spec.rb, hydra-head.gemspec, spec/test_app_templates/Gemfile.extra
- Bump rails/railties/activesupport to `< 8.1`
- Add ruby 3.4 / rails 8.0 / Blacklight 8 to circleci config (and update versions of other ruby / rails)
- Fix tests for Blacklight 8 changes
- Remove version restrictions on 3rd party gems
- Remove engine cart setup in Gemfile for older versions of rails (`< 6`)
- Pin concurrent-ruby in Gemfile / internal test app (not in gemspec)
- Add css processor flag to engine cart generation for rails 8
- Setup for solr 9.8+ in testing
=> Test on rails 8
